### PR TITLE
Some minor changes

### PR DESCRIPTION
**Pull request by sonic3XE**
* Implement experience_drain aura behavior.
* Minimap now renders removal and dummy zones with the respective colors.
* Experience variables are slightly changed.
* experience_draining is now experience_drain.

### CODE REVIEW

**Comment by sonic3XE** [comment]
Here is the [attached region file](https://cdn.discordapp.com/attachments/396977744434692106/1203328064763732028/withering-wasteland.yaml?ex=65ec6117&is=65d9ec17&hm=d17af513bdb3c5ef3b98d729e57792c9e12bd9f118aece0ef5a997d6a71c7ac5&) (Withering Wasteland)

**Comment by Pifary-dev** [comment]
Level calculation is incorrect here
It should be level 67 on area 41 without pellets, but here its level 41

Also what is the logic behind that?

```
calculateExperience(HeroLevel){
  return Math.floor(Math.min(HeroLevel,100)*Math.min(HeroLevel+1,101)*2+Math.max(0,HeroLevel*(HeroLevel+1)*(2*HeroLevel-179)/60-3535))
}
```

Just seems a bit random.

Apart from this experience stuff everything looks fine to me!

**Comment by sonic3XE** [comment]
level calculation should now be fixed.

**Comment by Pifary-dev** [comment]
It works well now, thanks for the changes!

**Pull request merged**
