### PR TITLE
Fixes to Magnetic Monopole

### PR DESCRIPTION
**Pull request by sonic3XE**
Recent issue (#6) was telling about problems in magnetic monopole.
This pull can be merged to resolve the said issue.

### CODE REVIEW

**Comment by Pifary-dev** [comment]
Well, there is a problem with coordinates since they aren't like in evades, portals teleport you not to places they are supposed to. For example, the down portal teleports you to RR.

**Comment by sonic3XE** [comment]
@Pifary-dev, should be fixed for now. (i also want to point out that portal on the left leads to the hard variant that was not there at the moment)

**Comment by sonic3XE** [comment]
okay, i added magnetic monopole hard. there should be no problem with the portals

**Comment by Pifary-dev** [comment]
It looks fine now, although there is no partial magnetism at the moment for mm2h. Thanks for the changes!

**Pull request merged**
