### PR TITLE
Allow enemies to have their default radius

### PR DESCRIPTION
**Pull request by sonic3XE**
We have updated the usage of radius whenever it is not specified. That is what I brought you Enemy Config that came from Evades.

### CODE REVIEW

**Comment by Pifary-dev** [comment]
Does it work on evades server as well?

**Comment by sonic3XE** [comment]
image
server-sided enemies have field_defaults function that falls back to default value of radius like dasher enemy for example as seen.

**Comment by Pifary-dev** [comment]
This is not what you think it is. If an enemy has a default radius, then the server does not need to send the radius of that enemy to the client. Server will crash if radius will not be specified (got confirmation from evades devs)

**Comment by sonic3XE** [comment]
okay then... i'll just close it anyways..

**Pull request closed without merging**
